# Generated by Django 4.1.3 on 2023-07-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closed', models.BooleanField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('isseller', models.BooleanField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProdeuct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapi.user'),
        ),
    ]
